### ISSUE TITLE
SecsVarString and None

### ISSUE THREAD

**Issue by massimov** [bparzella/secsgem#17]
It is possible to instantiate a SecsVarString having a value of None.
However it is not possible to use it practically: repr(), and len() (and therefore encode() and logging) all fail with exception:
TypeError: object of type 'NoneType' has no len()

__init__() and set() work because they make tests that prevent the TypeError.

The problem with this approach is that the error usually manifests itself far (in time and/or in code space) from assignment/creation, thus making it difficult to pinpoint the actual cause.

I suggest that either:
- if SecsVarStrings should not be instantiated with value None,  __init__ should raise an exception. In this case, at least it will happen at the point where the problem originates. This approach seems the easiest to implement.
- if a reasonable mapping to SEMI standards can be devised, None could be allowed provided all use cases are covered

**Comment by bparzella** [comment]
The value parameter of the SecsVarString constructor is an optional parameter, which defaults to None. In addition the default for the internal value is None. So the constructor will ignore the value if it is None, but it will be None anyways.

My suggestion would be:
* set constructors value parameter default to ""
* raise an ValueError exception if the value is intentionally set to None either by set or by constructor

Would this be close to what you expect?

**Comment by massimov** [comment]
Yes, more or less.
Just please take note that currently, __set__ method, if called with a parameter having type other than type string, will assign str(parameter).
Therefore, as things stand now, assigning None via __init__ and via __set__ causes different behaviour at later time, and this is one of the things I feel should be avoided.
I think that the way value parameter is handled by __init and __set__ should be the same, either:
a) raise a ValueError exception immediately (as opposed to have the exception raised ad a later time)
b) if type is not __str__, then take str(value) as __set__ does now also in __init__

So it eventually boils down to what should happen if one tries to set SecsVarString to a value that does not have type __str__ (not only __None__)

**Comment by bparzella** [comment]
I think anything else would be okay, because it is convertible to string. Especially float and int types should be accepted. Classes have the `__str__` member, so they are convertible too. Only thing I'm having mixed feelings about are list and dict.

**Comment by massimov** [comment]
Based on the current code, values must support __len__ as well.
"TypeError: object of type 'NoneType' has no len()" was the original cause that prompted me to post this issue

**Comment by bparzella** [comment]
That should be covered with the new implementation too. The value isn't None any more, and the str() is called in the set, which in return is called by the constructor. So if the set/constructor doesn't raise an ValueError the len should work on the value.
