### ISSUE TITLE
TCP_NODELAY

### ISSUE THREAD

**Issue by wolfc01** [bparzella/secsgem#2]
Hello Benjamin,

Just some backing info on the sockets:

please note that TCP_NODELAY disables the nagle algorith in the socket: that is, if the sender sends a small package, TCP IP will send this package immediately to the receiver. Normally nagle algorithm is ON, meaning that the TCP/IP stack (may) optimize by aggregating packets together in order to optimize throughput, but ruins timely passing of messages.

We use this option to have quick passing of small messages. 

I think with SECS/GEM this is not necessary to do, or am I wrong?

Best regards 
Carl.

**Comment by bparzella** [comment]
Hi Carl,

you might be right. I don't think the hsms protocol is that time critical.

Thank you again,
Benjamin
