### ISSUE TITLE
Is it possible to create script to run the regression test locally.

### ISSUE THREAD

**Issue by xianting77** [bparzella/secsgem#32]
1. If  want to run regression test with these testcase, where is entry point. Do I need to add following code in test .py file. Is it possible to create script to run the regression test locally. Do you add auto script at CI side?
if __name__ == '__main__':
    unittest.main(verbosity=2)    

2. after adding above code in test_secs_handler.py , got following information. Is this way right.

testSecsDecode (__main__.TestSecsHandler) ... ok
testSecsDecodeInvalidFunction (__main__.TestSecsHandler) ... unknown function S00F99
ok
testSecsDecodeInvalidStream (__main__.TestSecsHandler) ... unknown function S99F00
ok
testSecsDecodeNone (__main__.TestSecsHandler) ... ok
testStreamFunction (__main__.TestSecsHandler) ... ok
testStreamFunctionInvalidFunction (__main__.TestSecsHandler) ... unknown function S01F99
ok
testStreamFunctionInvalidStream (__main__.TestSecsHandler) ... unknown function S99F01
ok
testAreYouThere (__main__.TestSecsHandlerPassive) ... ok
testCallCallback (__main__.TestSecsHandlerPassive) ... ok
testCallbackIn (__main__.TestSecsHandlerPassive) ... ok
testDisableCeidReports (__main__.TestSecsHandlerPassive) ... ok
testDisableCeids (__main__.TestSecsHandlerPassive) ... ok
testExceptionFunctionCallback (__main__.TestSecsHandlerPassive) ... ok
testGetCeidName (__main__.TestSecsHandlerPassive) ... ok
testGetCeidNameMissingCeid (__main__.TestSecsHandlerPassive) ... ok
testGetCeidNameMissingName (__main__.TestSecsHandlerPassive) ... Callback aborted because of exception, abort sent
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\secsgem\secs\handler.py", line 222, in _handle_stream_function
    result = callback(self, packet)
  File "C:\Python38\lib\site-packages\secsgem\common\callbacks.py", line 25, in __call__
    return self.handler._call(self.name, *args, **kwargs)  # noqa
  File "C:\Python38\lib\site-packages\secsgem\common\callbacks.py", line 109, in _call
    return self._callbacks[callback](*args, **kwargs)
  File "C:\Python38\lib\site-packages\mock\mock.py", line 1100, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "C:\Python38\lib\site-packages\mock\mock.py", line 1104, in _mock_call
    return _mock_self._execute_mock_call(*args, **kwargs)
  File "C:\Python38\lib\site-packages\mock\mock.py", line 1161, in _execute_mock_call
    raise effect
Exception: testException
ok
testGetDvidName (__main__.TestSecsHandlerPassive) ... ok
testGetDvidNameMissingDvid (__main__.TestSecsHandlerPassive) ... ok
testGetDvidNameMissingName (__main__.TestSecsHandlerPassive) ... ok
testListECsAll (__main__.TestSecsHandlerPassive) ... ok
testListECsSpecific (__main__.TestSecsHandlerPassive) ... ok
testListSVsAll (__main__.TestSecsHandlerPassive) ... ok
testListSVsSpecific (__main__.TestSecsHandlerPassive) ... ok
testRegisterCallback (__main__.TestSecsHandlerPassive) ... ok
testRequestEC (__main__.TestSecsHandlerPassive) ... ok
testRequestECs (__main__.TestSecsHandlerPassive) ... ok
testRequestSV (__main__.TestSecsHandlerPassive) ... ok
testRequestSVs (__main__.TestSecsHandlerPassive) ... ok
testSendEquipmentTerminal (__main__.TestSecsHandlerPassive) ... ok
testSetEC (__main__.TestSecsHandlerPassive) ... ok
testSetECs (__main__.TestSecsHandlerPassive) ... ok
testStreamFunctionReceiving (__main__.TestSecsHandlerPassive) ... ok
testStreamFunctionReceivingExceptingCallback (__main__.TestSecsHandlerPassive) ... Callback aborted because of exception, abort sent
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\secsgem\secs\handler.py", line 222, in _handle_stream_function
    result = callback(self, packet)
  File "C:\Python38\lib\site-packages\secsgem\common\callbacks.py", line 25, in __call__
    return self.handler._call(self.name, *args, **kwargs)  # noqa
  File "C:\Python38\lib\site-packages\secsgem\common\callbacks.py", line 109, in _call
    return self._callbacks[callback](*args, **kwargs)
  File "C:\Python38\lib\site-packages\mock\mock.py", line 1100, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "C:\Python38\lib\site-packages\mock\mock.py", line 1104, in _mock_call
    return _mock_self._execute_mock_call(*args, **kwargs)
  File "C:\Python38\lib\site-packages\mock\mock.py", line 1161, in _execute_mock_call
    raise effect
Exception: testException
ok
testStreamFunctionReceivingUnhandledFunction (__main__.TestSecsHandlerPassive) ... unexpected function received s01f01
{sessionID:0x0000, stream:01, function:01, pType:0x00, sType:0x00, system:0x00000002, requireResponse:True}
ok
testStreamFunctionReceivingUnselected (__main__.TestSecsHandlerPassive) ... received message when not selected
ok
testStreamFunctionSending (__main__.TestSecsHandlerPassive) ... ok
testUnRegisterCallback (__main__.TestSecsHandlerPassive) ... ok
testUnhandeledFunctionCallback (__main__.TestSecsHandlerPassive) ... ok
testUnregisterStreamFunctionCallback (__main__.TestSecsHandlerPassive) ... ok
Callback aborted because of exception, abort sent
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\secsgem\secs\handler.py", line 224, in _handle_stream_function
    self.send_response(result, packet.header.system)
  File "C:\Python38\lib\site-packages\secsgem\hsms\handler.py", line 434, in send_response
    out_packet = HsmsPacket(HsmsStreamFunctionHeader(system, function.stream, function.function, False,
AttributeError: 'bool' object has no attribute 'stream'

----------------------------------------------------------------------
Ran 39 tests in 0.118s

OK

**Comment by bparzella** [comment]
I switched the test framework to tox and pytest recently. So the easiest way to run the tests locally would be to install the tox python package and simply run `tox` in the directory with the tox.ini present.

**Comment by xianting77** [comment]
Hi bparzella:




Thanks so much for your excellent secsgem lib and quick feedback about auto_test. I am studying of that (https://github.com/bparzella/secsgem),.

Firstly, I want to ask one question. I try following example, and I am considering the way to decode the secsgem.SecsS01F03([1,"1337",12]),  how you parse and print the result?

It is hard to trace the flow in SecsStreamFunction, you make it in __repr__(self) or decode(self, data) or other method? would you like let me know about the implementation when you are available?

 

>>> import secsgem

>>> secsgem.SecsS01F03

[

    SVID: U1/U2/U4/U8/I1/I2/I4/I8/A

    ...

]

>>> secsgem.SecsS01F03([1,"1337",12])

S1F3 W

  <L [3]

    <U1 1 >

    <A "1337">

    <U1 12 >

  > .

>>>




Any feedback from you are appreciated, looking forward your help.







At 2020-11-19 15:08:52, "Benjamin Parzella" <notifications@github.com> wrote:

I switched the test framework to tox and pytest recently. So the easiest way to run the tests locally would be to install the tox python package and simply run tox in the directory with the tox.ini present.

**Comment by bparzella** [comment]
Decoding is done with the decode() function and passed on to the configured data values for decoding the actual data. __repr__ is only for printing the data in a readable output.

**Comment by xianting77** [comment]
I use as host to connect my test equipment, I tried h.send_and_waitfor_response(secsgem.SecsS02F13([1628])) or h.send_and_waitfor_response(secsgem.SecsS01F01())  in console ,but seems received SxFx is not parse correctrly, do you have any suggestions


2020-11-20 15:25:51,961: > 'header': {sessionID:0x0000, stream:01, function:13, pType:0x00, sType:0x00, system:0xc5098891, requireResponse:True}
S1F13 W
  <L> .
2020-11-20 15:25:52,010: < 'header': {sessionID:0x0000, stream:01, function:14, pType:0x00, sType:0x00, system:0xc5098891, requireResponse:False}
S1F14
  <L [2]
    <B 0x0>
    <L [2]
      <A "IConnAu">
      <A "888473E93">
    >
  > .
2020-11-20 15:26:21,950: > 'header': {sessionID:0xffff, stream:00, function:00, pType:0x00, sType:0x05, system:0xc5098892, requireResponse:False}
  Linktest.req
2020-11-20 15:26:21,952: < 'header': {sessionID:0xffff, stream:00, function:00, pType:0x00, sType:0x06, system:0xc5098892, requireResponse:False}
  Linktest.rsp
2020-11-20 15:26:29,853: > 'header': {sessionID:0x0000, stream:02, function:13, pType:0x00, sType:0x00, system:0xc5098893, requireResponse:True}
S2F13 W
  <L [1]
    <U2 1628 >
  > .
2020-11-20 15:26:29,855: < 'header': {sessionID:0x0000, stream:02, function:00, pType:0x00, sType:0x00, system:0xc5098893, requireResponse:False}
S2F0 .

**Comment by xianting77** [comment]
another question is if i  connect my equipment with active mode, when does it send S1F13 
h = SampleHost("127.0.0.1", 5000, True, 0, "samplehost")

**Comment by bparzella** [comment]
> I use as host to connect my test equipment, I tried h.send_and_waitfor_response(secsgem.SecsS02F13([1628])) or h.send_and_waitfor_response(secsgem.SecsS01F01()) in console ,but seems received SxFx is not parse correctrly, do you have any suggestions
> 
> 2020-11-20 15:25:51,961: > 'header': {sessionID:0x0000, stream:01, function:13, pType:0x00, sType:0x00, system:0xc5098891, requireResponse:True}
> S1F13 W
> .
> 2020-11-20 15:25:52,010: < 'header': {sessionID:0x0000, stream:01, function:14, pType:0x00, sType:0x00, system:0xc5098891, requireResponse:False}
> S1F14
> <L [2]
> <B 0x0>
> <L [2]
> <A "IConnAu">
> <A "888473E93">
> >
> 
> > .
> > 2020-11-20 15:26:21,950: > 'header': {sessionID:0xffff, stream:00, function:00, pType:0x00, sType:0x05, system:0xc5098892, requireResponse:False}
> > Linktest.req
> > 2020-11-20 15:26:21,952: < 'header': {sessionID:0xffff, stream:00, function:00, pType:0x00, sType:0x06, system:0xc5098892, requireResponse:False}
> > Linktest.rsp
> > 2020-11-20 15:26:29,853: > 'header': {sessionID:0x0000, stream:02, function:13, pType:0x00, sType:0x00, system:0xc5098893, requireResponse:True}
> > S2F13 W
> > <L [1]
> > <U2 1628 >
> > .
> > 2020-11-20 15:26:29,855: < 'header': {sessionID:0x0000, stream:02, function:00, pType:0x00, sType:0x00, system:0xc5098893, requireResponse:False}
> > S2F0 .

S2F0 seems to be a valid answer, F0 usually is an abort transaction.

**Comment by bparzella** [comment]
> another question is if i connect my equipment with active mode, when does it send S1F13
> h = SampleHost("127.0.0.1", 5000, True, 0, "samplehost")

S1F13 is sent when the connection state changes to WAIT_CRA: https://github.com/bparzella/secsgem/blob/62ceb479257b0e71bae5656b274ef15e1a362513/secsgem/gem/handler.py#L170

**Comment by xianting77** [comment]
> 2F0 seems to be a valid answer, F0 usually is an abort transaction.

just a little bit confusion, why the command send in code (self.send_stream_function(self.stream_function(1, 13)()))  can be recognized by equipment, why i send it at  console, it can not. 
I tried either 
h.send_stream_function(h.stream_function(1, 1)())
h.send_stream_function(h.stream_function(2, 13)([1628]))

or 
h.send_and_waitfor_response(secsgem.SecsS01F01())
What is the problem i made, How can interact with my equipment with the sample example/
Thanks for your time.

**Comment by bparzella** [comment]
2020-11-20 15:26:29,853: > 'header': {sessionID:0x0000, stream:02, function:13, pType:0x00, sType:0x00, system:0xc5098893, requireResponse:True}
S2F13 W
<L [1]
  <U2 1628 >
.
2020-11-20 15:26:29,855: < 'header': {sessionID:0x0000, stream:02, function:00, pType:0x00, sType:0x00, system:0xc5098893, requireResponse:False}
S2F0 .

It looks like your equipment answers your request with an s02e00, which is an abort transactions.

This indicates that the equipment is not happy with this message. You should find out what your equipment expects and why it doesn't accept this function.

**Comment by xianting77** [comment]
> 2020-11-20 15:26:29,853: > 'header': {sessionID:0x0000, stream:02, function:13, pType:0x00, sType:0x00, system:0xc5098893, requireResponse:True}
> S2F13 W
> <L [1]
> <U2 1628 >
> .
> 2020-11-20 15:26:29,855: < 'header': {sessionID:0x0000, stream:02, function:00, pType:0x00, sType:0x00, system:0xc5098893, requireResponse:False}
> S2F0 .
> 
> It looks like your equipment answers your request with an s02e00, which is an abort transaction.
> 
> This indicates that the equipment is not happy with this message. You should find out what your equipment expects and why it doesn't accept this function.

Thanks for your reply, i find the reason, I missed to let my equipment go online/ 
After go online ,everything is ok.

2020-11-20 19:20:20,766: > 'header': {sessionID:0x0000, stream:01, function:01, pType:0x00, sType:0x00, system:0xedf9e649, requireResponse:True}
S1F1 W .
2020-11-20 19:20:20,809: < 'header': {sessionID:0x0000, stream:01, function:02, pType:0x00, sType:0x00, system:0xedf9e649, requireResponse:False}
S1F2
  <L [2]
    <A "IConnAu">
    <A "888473E93">
  > .
2020-11-20 19:20:48,637: > 'header': {sessionID:0xffff, stream:00, function:00, pType:0x00, sType:0x05, system:0xedf9e64a, requireResponse:False}
  Linktest.req
2020-11-20 19:20:48,639: < 'header': {sessionID:0xffff, stream:00, function:00, pType:0x00, sType:0x06, system:0xedf9e64a, requireResponse:False}
  Linktest.rsp
2020-11-20 19:21:10,615: > 'header': {sessionID:0x0000, stream:07, function:19, pType:0x00, sType:0x00, system:0xedf9e64b, requireResponse:True}
S7F19 W .
2020-11-20 19:21:10,664: < 'header': {sessionID:0x0000, stream:07, function:20, pType:0x00, sType:0x00, system:0xedf9e64b, requireResponse:False}
S7F20
  <L [10]
    <A "MHS_68LD.BND">
    <A "BUMP.BND">
    <A "MHS_DFLT.BND">
    <A "STDBGA.BND">
    <A "MHS_CURR.BND">
    <A "10116EXT.BND">
    <A "STD208LD.BND">
    <A "MHS_208.BND">
    <A "STD68LD.BND">
    <A "MTRX.BND">
  > .

From this test I learn two thing.
1. S1F13/F14 can work if remote is not online, seems other command need remote "go online"
2.  use send_stream_function() instead of  send_and_waitfor_response, the first seems more stable, refer following test

>>> h.send_and_waitfor_response(secsgem.SecsS02F13([1628]))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python38\lib\site-packages\secsgem\hsms\packets.py", line 409, in __repr__
    self.data.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 2: invalid start byte
>>> h.send_stream_function(secsgem.SecsS02F13([1628]))
True
>>> 2020-11-20 19:28:45,389 __main__.SampleHost._handle_stream_function: unexpected function received s02f14
{sessionID:0x0000, stream:02, function:14, pType:0x00, sType:0x00, system:0xedf9e661, requireResponse:False}
