### ISSUE TITLE
No module named 'communication_log_file_handler'

### ISSUE THREAD

**Issue by qingfengyilin** [bparzella/secsgem#33]
After  "pip install secsgem", when I run the sample code, python couldn't find module named 'communication_log_file_handler'.  Should I install another module?

**Comment by thisch** [comment]
@qingfengyilin I just had the same issue. the file is part of the samples directory https://github.com/bparzella/secsgem/blob/443cc157d7f96c9de891df2bd079b2cde0747e4d/samples/communication_log_file_handler.py
