### ISSUE TITLE
ImportError: No module named gem

### ISSUE THREAD

**Issue by xiping0414** [bparzella/secsgem#34]
In python 2.7, I installed using **pip install secsgem**

`import secsgem.gem

class SampleHost(secsgem.gem.GemHostHandler):
    def __init__(self, address, port, active, session_id, name, custom_connection_handler=None):
        secsgem.gem.GemHostHandler.__init__(self, address, port, active, session_id, name, custom_connection_handler)

        self.MDLN = "gemhost"
        self.SOFTREV = "1.0.0"`

I am getting following error
Traceback (most recent call last):
  File "E:/20170622/secsgem.py", line 5, in <module>
    import secsgem.gem
  File "E:\20170622\secsgem.py", line 5, in <module>
    import secsgem.gem
ImportError: No module named gem

Process finished with exit code 1

**Comment by bparzella** [comment]
You named your source file same as the package name (secsgem.py). So python tries to import your source file instead of the secsgem package, kind of a recursive import.
