### ISSUE TITLE
ImportError: No module named 'hsms'

### ISSUE THREAD

**Issue by ttchin** [bparzella/secsgem#4]
I have pip installed secsgem, and I'm using Python3.5.1 on windows 7 bit32.
>>> from secsgem import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Programs Files\Python\Python35-32\lib\site-packages\secsgem\__init__.
py", line 17, in <module>
    from hsms import *
ImportError: No module named 'hsms'

**Comment by bparzella** [comment]
secsgem is not compatible with python 3 at the moment. i haven't tested it with windows yet, os x and linux are working.
